version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30377:3344"
    links:
      - py
    depends_on:
      - py
    volumes:
      - ./data:/app/data

  py:
    restart: always
    build:
      context: ./python
      dockerfile: Dockerfile
    shm_size: '1gb'
    volumes:
      - ./python/data:/app/data
